name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.gif?color_snake=#ffce02
            dist/github-snake-dark.gif?palette=github-dark&color_snake=#ffce02
      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[AUTOMATIC] Generate snake animation'
          file_pattern: 'dist/*'
